export default [
  {
    files: ["**/*.{ts,tsx}"],
    ignores: [
      "**/*.log",
      "**/.DS_Store",
      "*.",
      ".vscode/settings.json",
      ".history",
      ".yarn",
      "bazel-*",
      "bazel-bin",
      "bazel-out",
      "bazel-qwik",
      "bazel-testlogs",
      "dist",
      "dist-dev",
      "lib",
      "lib-types",
      "etc",
      "external",
      "node_modules",
      "temp",
      "tsc-out",
      "tsdoc-metadata.json",
      "target",
      "output",
      "rollup.config.js",
      "build",
      ".cache",
      ".vscode",
      ".rollup.cache",
      "dist",
      "tsconfig.tsbuildinfo",
      "vite.config.ts",
      "*.spec.tsx",
      "*.spec.ts",
      "*.css",
      ".netlify",
      "pnpm-lock.yaml",
      "package-lock.json",
      "yarn.lock",
      "server",
      "package.json",
    ],
    root: true,
    env: {
      browser: true,
      es2021: true,
      node: true,
    },
    extends: ["@todomir/eslint-config", "plugin:qwik/recommended", "prettier"],
    parser: "@typescript-eslint/parser",
    parserOptions: {
      project: ["./tsconfig.json"],
      ecmaVersion: 2_021,
      sourceType: "module",
      ecmaFeatures: {
        jsx: true,
      },
    },
    rules: {
      "no-inline-comments": "off",
      "unicorn/prevent-abbreviations": "off",
      "@typescript-eslint/prefer-nullish-coalescing": "off",
    },
  },
];
